config/routes.rb
Rails.application.routes.draw do
  root to: 'users#home'

  devise_for :users
  resources :users do
    get 'admin', on: :collection
    get 'home', on: :collection
  end

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  require 'sidekiq/web'
  require 'sidekiq-status/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :inputs, only: [:index, :show] do
    get 'datafields'
    match 'datafields' => 'inputs#datafields', :via => [:get, :post]
  end

  get 'wizard' => 'projects#wizard'
  resources :buildings
  resources :projects do
    get 'download', on: :member
  end

  # TODO:  restrict to needed routes only (bulk_sync, index, show)

  # these belong to project. may not need routes for them
  resources :materials
  resources :construct_assemblies
  resources :door_constructions
  resources :fenestration_constructions
  resources :luminaires, only: [:index, :show] do
    post 'bulk_sync', on: :collection
  end

  # libraries
  resources :constructions, only: [:show, :index]
  resources :fenestrations, only: [:show, :index]
  resources :door_lookups, only: [:show, :index]
  resources :space_function_defaults, only: [:show, :index]
  resources :zip_codes, only: [:show, :index]

  # depend on project
  resources :construction_defaults     # only index, create for angular

  # depend on building
  resources :building_stories do
    post 'bulk_sync', on: :collection
  end

  # this handles air and zone systems
  resources :zone_systems do
    post 'bulk_sync', on: :collection
  end
  resources :fluid_systems do
    post 'bulk_sync', on: :collection
  end
  resources :spaces do
    post 'bulk_sync', on: :collection
  end
  resources :simulations, only: [:show, :index] do
    get 'download_report', on: :member
    post 'bulk_sync', on: :collection
  end
  resources :thermal_zones do
    post 'bulk_sync', on: :collection
  end
  resources :terminal_units do
    post 'bulk_sync', on: :collection
  end

  # don't need direct routes for these (accessed through other controllers)
  # resources :air_systems
  # resources :windows
  # resources :underground_floors
  # resources :fans
  # resources :coil_coolings
  # resources :air_segments
  # resources :roofs
  # resources :ceilings
  # resources :heat_rejections
  # resources :interior_walls
  # resources :exterior_floors
  # resources :pumps
  # resources :boilers
  # resources :chillers
  # resources :fluid_segments
  # resources :coil_heatings
  # resources :doors
  # resources :skylights
  # resources :underground_walls
  # resources :interior_floors
  # resources :exterior_walls
  # resources :interior_lighting_systems
  # resources :outside_air_controls
  # resources :water_heaters

  # non-revised below
  #   resources :holidays
  #
  #   resources :design_days
  #
  #   resources :recirculation_water_heaters
  #
  #   resources :recirculation_dhw_systems
  #
  #   resources :evaporative_coolers
  #
  #   resources :external_shading_objects
  #
  #   resources :curve_double_quadratics
  #
  #   resources :curve_linears
  #
  #   resources :schedules
  #
  #   resources :curve_cubics
  #
  #   resources :curve_quadratics
  #
  #   resources :schedule_weeks
  #
  #   resources :schedule_days
  #
  #   resources :cartesian_points
  #
  #   resources :poly_loops
end

app/models/fenestration_construction.rb
class FenestrationConstruction
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :fenestration_type, type: String
  field :fenestration_product_type, type: String
  field :assembly_context, type: String
  field :certification_method, type: String
  field :skylight_glazing, type: String
  field :skylight_curb, type: String
  field :operable_window_configuration, type: String
  field :greenhouse_garden_window, type: Integer
  field :fenestration_framing, type: String
  field :fenestration_panes, type: String
  field :glazing_tint, type: String
  field :window_divider, type: String
  field :diffusing, type: Integer
  field :shgc, type: Float
  field :shgc_center_of_glass, type: Float
  field :u_factor, type: Float
  field :u_factor_center_of_glass, type: Float
  field :visible_transmittance, type: Float
  field :visible_transmittance_center_of_glass, type: Float

  belongs_to :project

  def self.children_models
    children = [

    ]
  end

  def self.xml_fields
    xml_fields = [
      { db_field_name: 'name', xml_field_name: 'Name' },
      { db_field_name: 'fenestration_type', xml_field_name: 'FenType' },
      { db_field_name: 'fenestration_product_type', xml_field_name: 'FenProdType' },
      { db_field_name: 'assembly_context', xml_field_name: 'AssmContext' },
      { db_field_name: 'certification_method', xml_field_name: 'CertificationMthd' },
      { db_field_name: 'skylight_glazing', xml_field_name: 'SkyltGlz' },
      { db_field_name: 'skylight_curb', xml_field_name: 'SkyltCurb' },
      { db_field_name: 'operable_window_configuration', xml_field_name: 'OperableWinConfiguration' },
      { db_field_name: 'greenhouse_garden_window', xml_field_name: 'GreenhouseGardenWin' },
      { db_field_name: 'fenestration_framing', xml_field_name: 'FenFrm' },
      { db_field_name: 'fenestration_panes', xml_field_name: 'FenPanes' },
      { db_field_name: 'glazing_tint', xml_field_name: 'GlzTint' },
      { db_field_name: 'window_divider', xml_field_name: 'WinDivider' },
      { db_field_name: 'diffusing', xml_field_name: 'Diffusing' },
      { db_field_name: 'shgc', xml_field_name: 'SHGC' },
      { db_field_name: 'shgc_center_of_glass', xml_field_name: 'SHGCCOG' },
      { db_field_name: 'u_factor', xml_field_name: 'UFactor' },
      { db_field_name: 'u_factor_center_of_glass', xml_field_name: 'UFactorCOG' },
      { db_field_name: 'visible_transmittance', xml_field_name: 'VT' },
      { db_field_name: 'visible_transmittance_center_of_glass', xml_field_name: 'VTCOG' }
    ]
  end

  # This method is autogenerated. Do not change directly.
  def to_sdd_xml(meta, xml)
    xml.send(meta[:xml_name]) do
      self.class.xml_fields.each do |field|
        if self[field[:db_field_name]]
          if self[field[:db_field_name]].is_a? Array
            logger.debug 'Translating to XML and the object is an Array'
            self[field[:db_field_name]].each_with_index do |instance, index|
              xml.send(:"#{field[:xml_field_name]}", instance, 'index' => index)
            end
          else
            xml.send(:"#{field[:xml_field_name]}", self[field[:db_field_name]])
          end
        end
      end

      # go through children if they have something to add, call their methods
      kids = self.class.children_models
      unless kids.nil? || kids.empty?
        kids.each do |k|
          models = send(k[:model_name].pluralize)
          models.each do |m|
            m.to_sdd_xml(k, xml)
          end
        end
      end
    end
  end

  # This method is autogenerated. Do not change directly.
  # Take the map of model name and xml name, and the hash (from the XML).
  def self.from_sdd_json(meta, h)
    o = nil
    if meta && h
      self_model = meta[:model_name].camelcase(:upper).constantize
      o = self_model.create_from_sdd_json(meta, h)
      if o
        o.create_children_from_sdd_json(meta, h)
        o.save!
        o.reload # in case of relationships being updated
      else
        fail "Could not create instance of #{self_model} for #{meta[:model_name]}"
      end
    end

    o
  end

  # This method is autogenerated. Do not change directly.
  def self.create_from_sdd_json(meta, h)
    new_h = {}

    # Find fields as defined by the XML
    self_model = meta[:model_name].camelcase(:upper).constantize
    self_model.xml_fields.each do |field|
      if h[field[:xml_field_name]]
        logger.debug "Field Data Type: #{self_model.fields[field[:db_field_name]].options[:type]}"
        if self_model.fields[field[:db_field_name]].options[:type].to_s == 'Array'
          logger.debug 'Data model has an array as the field'
          # check if the hash has an array, otherwise make it an array
          if h[field[:xml_field_name]].is_a? Array
            logger.debug 'XML/JSON field is already an Array'
            new_h[field[:db_field_name]] = h[field[:xml_field_name]]
          else
            new_h[field[:db_field_name]] = [h[field[:xml_field_name]]]
          end
        else
          new_h[field[:db_field_name]] = h[field[:xml_field_name]]
        end
      end
    end

    # new_h can be empty if the xml has no fields, but still create the object
    o = self_model.new(new_h)

    o
  end

  # This method is autogenerated. Do not change directly.
  def create_children_from_sdd_json(meta, h)
    # Go through the children
    self_model = meta[:model_name].camelcase(:upper).constantize
    kids = self_model.children_models
    unless kids.nil? || kids.empty?
      kids.each do |k|
        # check if the kids have a json object at this level
        if h[k[:xml_name]]
          logger.debug "XML child is #{k[:xml_name]}"
          logger.debug "Model name is #{k[:model_name]}"
          if h[k[:xml_name]].is_a? Array
            logger.debug "#{k[:xml_name]} is an array, will add all the objects"
            h[k[:xml_name]].each do |h_instance|
              klass = k[:model_name].camelcase(:upper).constantize
              if klass.respond_to? :from_sdd_json
                model = klass.from_sdd_json(k, h_instance)

                # Assign the foreign key on the object
                model["#{meta[:model_name]}_id"] = id
                model.save!
              else
                logger.warn "Class #{klass} does not have instance method 'from_sdd_json'"
              end
            end
          elsif h[k[:xml_name]].is_a? Hash
            logger.debug "#{k[:xml_name]} is a single object, will add only one"
            klass = k[:model_name].camelcase(:upper).constantize
            if klass.respond_to? :from_sdd_json
              model = klass.from_sdd_json(k, h[k[:xml_name]])

              # Assign the foreign key on the object
              model["#{meta[:model_name]}_id"] = id
              model.save!
            else
              logger.warn "Class #{klass} does not have instance method 'from_sdd_json'"
            end
          end
        end
      end
    end
  end

  def fenestration_type_enums
    %w(VerticalFenestration Skylight)
  end

  def assembly_context_enums
    %w(Manufactured FieldFabricated SiteBuilt)
  end

  def operable_window_configuration_enums
    [
      '- specify -',
      'CasementAwning',
      'Sliding'
    ]
  end

  def window_divider_enums
    [
      '- specify -',
      'TrueDividedLite',
      'DividerBtwnPanesLessThan7_16in',
      'DividerBtwnPanesGreaterThanOrEqualTo7_16in'
    ]
  end
end

app/controllers/fenestration_constructions_controller.rb
class FenestrationConstructionsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource param_method: :fenestration_construction_params
  before_action :set_fenestration_construction, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @fenestration_constructions = FenestrationConstruction.all
    respond_with(@fenestration_constructions)
  end

  def show
    respond_with(@fenestration_construction)
  end

  def new
    @fenestration_construction = FenestrationConstruction.new
    respond_with(@fenestration_construction)
  end

  def edit
  end

  def create
    @fenestration_construction = FenestrationConstruction.new(fenestration_construction_params)
    @fenestration_construction.save
    respond_with(@fenestration_construction)
  end

  def update
    @fenestration_construction.update(fenestration_construction_params)
    respond_with(@fenestration_construction)
  end

  def destroy
    @fenestration_construction.destroy
    respond_with(@fenestration_construction)
  end

  private

  def set_fenestration_construction
    @fenestration_construction = FenestrationConstruction.find(params[:id])
  end

  def fenestration_construction_params
    params.require(:fenestration_construction).permit(:name, :fenestration_type, :fenestration_product_type, :assembly_context, :certification_method, :skylight_glazing, :skylight_curb, :operable_window_configuration, :greenhouse_garden_window, :fenestration_framing, :fenestration_panes, :glazing_tint, :window_divider, :diffusing, :shgc, :shgc_center_of_glass, :u_factor, :u_factor_center_of_glass, :visible_transmittance, :visible_transmittance_center_of_glass)
  end
end

app/views/fenestration_constructions/_form.html.erb
<%= form_for(@fenestration_construction) do |f| %>
  <% if @fenestration_construction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fenestration_construction.errors.count, "error") %> prohibited this fenestration_construction from being saved:</h2>

      <ul>
      <% @fenestration_construction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :fenestration_type %><br>
    <%= f.text_field :fenestration_type %>
  </div>
  <div class="field">
    <%= f.label :fenestration_product_type %><br>
    <%= f.text_field :fenestration_product_type %>
  </div>
  <div class="field">
    <%= f.label :assembly_context %><br>
    <%= f.text_field :assembly_context %>
  </div>
  <div class="field">
    <%= f.label :certification_method %><br>
    <%= f.text_field :certification_method %>
  </div>
  <div class="field">
    <%= f.label :skylight_glazing %><br>
    <%= f.text_field :skylight_glazing %>
  </div>
  <div class="field">
    <%= f.label :skylight_curb %><br>
    <%= f.text_field :skylight_curb %>
  </div>
  <div class="field">
    <%= f.label :operable_window_configuration %><br>
    <%= f.text_field :operable_window_configuration %>
  </div>
  <div class="field">
    <%= f.label :greenhouse_garden_window %><br>
    <%= f.text_field :greenhouse_garden_window %>
  </div>
  <div class="field">
    <%= f.label :fenestration_framing %><br>
    <%= f.text_field :fenestration_framing %>
  </div>
  <div class="field">
    <%= f.label :fenestration_panes %><br>
    <%= f.text_field :fenestration_panes %>
  </div>
  <div class="field">
    <%= f.label :glazing_tint %><br>
    <%= f.text_field :glazing_tint %>
  </div>
  <div class="field">
    <%= f.label :window_divider %><br>
    <%= f.text_field :window_divider %>
  </div>
  <div class="field">
    <%= f.label :diffusing %><br>
    <%= f.text_field :diffusing %>
  </div>
  <div class="field">
    <%= f.label :shgc %><br>
    <%= f.text_field :shgc %>
  </div>
  <div class="field">
    <%= f.label :shgc_center_of_glass %><br>
    <%= f.text_field :shgc_center_of_glass %>
  </div>
  <div class="field">
    <%= f.label :u_factor %><br>
    <%= f.text_field :u_factor %>
  </div>
  <div class="field">
    <%= f.label :u_factor_center_of_glass %><br>
    <%= f.text_field :u_factor_center_of_glass %>
  </div>
  <div class="field">
    <%= f.label :visible_transmittance %><br>
    <%= f.text_field :visible_transmittance %>
  </div>
  <div class="field">
    <%= f.label :visible_transmittance_center_of_glass %><br>
    <%= f.text_field :visible_transmittance_center_of_glass %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fenestration_constructions/edit.html.erb
<h1>Editing fenestration_construction</h1>

<%= render 'form' %>

<%= link_to 'Show', @fenestration_construction %> |
<%= link_to 'Back', fenestration_constructions_path %>

app/views/fenestration_constructions/index.html.erb
<h1>Listing fenestration_constructions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fenestration type</th>
      <th>Fenestration product type</th>
      <th>Assembly context</th>
      <th>Certification method</th>
      <th>Skylight glazing</th>
      <th>Skylight curb</th>
      <th>Operable window configuration</th>
      <th>Greenhouse garden window</th>
      <th>Fenestration framing</th>
      <th>Fenestration panes</th>
      <th>Glazing tint</th>
      <th>Window divider</th>
      <th>Diffusing</th>
      <th>Shgc</th>
      <th>Shgc center of glass</th>
      <th>U factor</th>
      <th>U factor center of glass</th>
      <th>Visible transmittance</th>
      <th>Visible transmittance center of glass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fenestration_constructions.each do |fenestration_construction| %>
      <tr>
        <td><%= fenestration_construction.name %></td>
        <td><%= fenestration_construction.fenestration_type %></td>
        <td><%= fenestration_construction.fenestration_product_type %></td>
        <td><%= fenestration_construction.assembly_context %></td>
        <td><%= fenestration_construction.certification_method %></td>
        <td><%= fenestration_construction.skylight_glazing %></td>
        <td><%= fenestration_construction.skylight_curb %></td>
        <td><%= fenestration_construction.operable_window_configuration %></td>
        <td><%= fenestration_construction.greenhouse_garden_window %></td>
        <td><%= fenestration_construction.fenestration_framing %></td>
        <td><%= fenestration_construction.fenestration_panes %></td>
        <td><%= fenestration_construction.glazing_tint %></td>
        <td><%= fenestration_construction.window_divider %></td>
        <td><%= fenestration_construction.diffusing %></td>
        <td><%= fenestration_construction.shgc %></td>
        <td><%= fenestration_construction.shgc_center_of_glass %></td>
        <td><%= fenestration_construction.u_factor %></td>
        <td><%= fenestration_construction.u_factor_center_of_glass %></td>
        <td><%= fenestration_construction.visible_transmittance %></td>
        <td><%= fenestration_construction.visible_transmittance_center_of_glass %></td>
        <td><%= link_to 'Show', fenestration_construction %></td>
        <td><%= link_to 'Edit', edit_fenestration_construction_path(fenestration_construction) %></td>
        <td><%= link_to 'Destroy', fenestration_construction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fenestration construction', new_fenestration_construction_path %>

app/views/fenestration_constructions/new.html.erb
<h1>New fenestration_construction</h1>

<%= render 'form' %>

<%= link_to 'Back', fenestration_constructions_path %>

app/views/fenestration_constructions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fenestration_construction.name %>
</p>

<p>
  <strong>Fenestration type:</strong>
  <%= @fenestration_construction.fenestration_type %>
</p>

<p>
  <strong>Fenestration product type:</strong>
  <%= @fenestration_construction.fenestration_product_type %>
</p>

<p>
  <strong>Assembly context:</strong>
  <%= @fenestration_construction.assembly_context %>
</p>

<p>
  <strong>Certification method:</strong>
  <%= @fenestration_construction.certification_method %>
</p>

<p>
  <strong>Skylight glazing:</strong>
  <%= @fenestration_construction.skylight_glazing %>
</p>

<p>
  <strong>Skylight curb:</strong>
  <%= @fenestration_construction.skylight_curb %>
</p>

<p>
  <strong>Operable window configuration:</strong>
  <%= @fenestration_construction.operable_window_configuration %>
</p>

<p>
  <strong>Greenhouse garden window:</strong>
  <%= @fenestration_construction.greenhouse_garden_window %>
</p>

<p>
  <strong>Fenestration framing:</strong>
  <%= @fenestration_construction.fenestration_framing %>
</p>

<p>
  <strong>Fenestration panes:</strong>
  <%= @fenestration_construction.fenestration_panes %>
</p>

<p>
  <strong>Glazing tint:</strong>
  <%= @fenestration_construction.glazing_tint %>
</p>

<p>
  <strong>Window divider:</strong>
  <%= @fenestration_construction.window_divider %>
</p>

<p>
  <strong>Diffusing:</strong>
  <%= @fenestration_construction.diffusing %>
</p>

<p>
  <strong>Shgc:</strong>
  <%= @fenestration_construction.shgc %>
</p>

<p>
  <strong>Shgc center of glass:</strong>
  <%= @fenestration_construction.shgc_center_of_glass %>
</p>

<p>
  <strong>U factor:</strong>
  <%= @fenestration_construction.u_factor %>
</p>

<p>
  <strong>U factor center of glass:</strong>
  <%= @fenestration_construction.u_factor_center_of_glass %>
</p>

<p>
  <strong>Visible transmittance:</strong>
  <%= @fenestration_construction.visible_transmittance %>
</p>

<p>
  <strong>Visible transmittance center of glass:</strong>
  <%= @fenestration_construction.visible_transmittance_center_of_glass %>
</p>

<%= link_to 'Edit', edit_fenestration_construction_path(@fenestration_construction) %> |
<%= link_to 'Back', fenestration_constructions_path %>