config/routes.rb
Rails.application.routes.draw do
  root to: 'users#home'

  devise_for :users
  resources :users do
    get 'admin', on: :collection
    get 'home', on: :collection
  end

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

  require 'sidekiq/web'
  require 'sidekiq-status/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :inputs, only: [:index, :show] do
    get 'datafields'
    match 'datafields' => 'inputs#datafields', :via => [:get, :post]
  end

  get 'wizard' => 'projects#wizard'
  resources :buildings
  resources :projects do
    get 'download', on: :member
  end

  # TODO:  restrict to needed routes only (bulk_sync, index, show)

  # these belong to project. may not need routes for them
  resources :materials
  resources :construct_assemblies
  resources :door_constructions
  resources :fenestration_constructions
  resources :luminaires, only: [:index, :show] do
    post 'bulk_sync', on: :collection
  end

  # libraries
  resources :constructions, only: [:show, :index]
  resources :fenestrations, only: [:show, :index]
  resources :door_lookups, only: [:show, :index]
  resources :space_function_defaults, only: [:show, :index]
  resources :zip_codes, only: [:show, :index]

  # depend on project
  resources :construction_defaults     # only index, create for angular

  # depend on building
  resources :building_stories do
    post 'bulk_sync', on: :collection
  end

  # this handles air and zone systems
  resources :zone_systems do
    post 'bulk_sync', on: :collection
  end
  resources :fluid_systems do
    post 'bulk_sync', on: :collection
  end
  resources :spaces do
    post 'bulk_sync', on: :collection
  end
  resources :simulations, only: [:show, :index] do
    get 'download_report', on: :member
    post 'bulk_sync', on: :collection
  end
  resources :thermal_zones do
    post 'bulk_sync', on: :collection
  end
  resources :terminal_units do
    post 'bulk_sync', on: :collection
  end

  # don't need direct routes for these (accessed through other controllers)
  # resources :air_systems
  # resources :windows
  # resources :underground_floors
  # resources :fans
  # resources :coil_coolings
  # resources :air_segments
  # resources :roofs
  # resources :ceilings
  # resources :heat_rejections
  # resources :interior_walls
  # resources :exterior_floors
  # resources :pumps
  # resources :boilers
  # resources :chillers
  # resources :fluid_segments
  # resources :coil_heatings
  # resources :doors
  # resources :skylights
  # resources :underground_walls
  # resources :interior_floors
  # resources :exterior_walls
  # resources :interior_lighting_systems
  # resources :outside_air_controls
  # resources :water_heaters

  # non-revised below
  #   resources :holidays
  #
  #   resources :design_days
  #
  #   resources :recirculation_water_heaters
  #
  #   resources :recirculation_dhw_systems
  #
  #   resources :evaporative_coolers
  #
  #   resources :external_shading_objects
  #
  #   resources :curve_double_quadratics
  #
  #   resources :curve_linears
  #
  #   resources :schedules
  #
  #   resources :curve_cubics
  #
  #   resources :curve_quadratics
  #
  #   resources :schedule_weeks
  #
  #   resources :schedule_days
  #
  #   resources :cartesian_points
  #
  #   resources :poly_loops
end

app/models/luminaire.rb
class Luminaire
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :fixture_type, type: String
  field :lamp_type, type: String
  field :power, type: Float
  field :heat_gain_space_fraction, type: Float
  field :heat_gain_radiant_fraction, type: Float

  belongs_to :project

  def self.children_models
    children = [

    ]
  end

  def self.xml_fields
    xml_fields = [
      { db_field_name: 'name', xml_field_name: 'Name' },
      { db_field_name: 'fixture_type', xml_field_name: 'FxtrType' },
      { db_field_name: 'lamp_type', xml_field_name: 'LampType' },
      { db_field_name: 'power', xml_field_name: 'Pwr' },
      { db_field_name: 'heat_gain_space_fraction', xml_field_name: 'HtGnSpcFrac' },
      { db_field_name: 'heat_gain_radiant_fraction', xml_field_name: 'HtGnRadFrac' }
    ]
  end

  # This method is autogenerated. Do not change directly.
  def to_sdd_xml(meta, xml)
    xml.send(meta[:xml_name]) do
      self.class.xml_fields.each do |field|
        if self[field[:db_field_name]]
          if self[field[:db_field_name]].is_a? Array
            logger.debug 'Translating to XML and the object is an Array'
            self[field[:db_field_name]].each_with_index do |instance, index|
              xml.send(:"#{field[:xml_field_name]}", instance, 'index' => index)
            end
          else
            xml.send(:"#{field[:xml_field_name]}", self[field[:db_field_name]])
          end
        end
      end

      # go through children if they have something to add, call their methods
      kids = self.class.children_models
      unless kids.nil? || kids.empty?
        kids.each do |k|
          models = send(k[:model_name].pluralize)
          models.each do |m|
            m.to_sdd_xml(k, xml)
          end
        end
      end
    end
  end

  # This method is autogenerated. Do not change directly.
  # Take the map of model name and xml name, and the hash (from the XML).
  def self.from_sdd_json(meta, h)
    o = nil
    if meta && h
      self_model = meta[:model_name].camelcase(:upper).constantize
      o = self_model.create_from_sdd_json(meta, h)
      if o
        o.create_children_from_sdd_json(meta, h)
        o.save!
        o.reload # in case of relationships being updated
      else
        fail "Could not create instance of #{self_model} for #{meta[:model_name]}"
      end
    end

    o
  end

  # This method is autogenerated. Do not change directly.
  def self.create_from_sdd_json(meta, h)
    new_h = {}

    # Find fields as defined by the XML
    self_model = meta[:model_name].camelcase(:upper).constantize
    self_model.xml_fields.each do |field|
      if h[field[:xml_field_name]]
        logger.debug "Field Data Type: #{self_model.fields[field[:db_field_name]].options[:type]}"
        if self_model.fields[field[:db_field_name]].options[:type].to_s == 'Array'
          logger.debug 'Data model has an array as the field'
          # check if the hash has an array, otherwise make it an array
          if h[field[:xml_field_name]].is_a? Array
            logger.debug 'XML/JSON field is already an Array'
            new_h[field[:db_field_name]] = h[field[:xml_field_name]]
          else
            new_h[field[:db_field_name]] = [h[field[:xml_field_name]]]
          end
        else
          new_h[field[:db_field_name]] = h[field[:xml_field_name]]
        end
      end
    end

    # new_h can be empty if the xml has no fields, but still create the object
    o = self_model.new(new_h)

    o
  end

  # This method is autogenerated. Do not change directly.
  def create_children_from_sdd_json(meta, h)
    # Go through the children
    self_model = meta[:model_name].camelcase(:upper).constantize
    kids = self_model.children_models
    unless kids.nil? || kids.empty?
      kids.each do |k|
        # check if the kids have a json object at this level
        if h[k[:xml_name]]
          logger.debug "XML child is #{k[:xml_name]}"
          logger.debug "Model name is #{k[:model_name]}"
          if h[k[:xml_name]].is_a? Array
            logger.debug "#{k[:xml_name]} is an array, will add all the objects"
            h[k[:xml_name]].each do |h_instance|
              klass = k[:model_name].camelcase(:upper).constantize
              if klass.respond_to? :from_sdd_json
                model = klass.from_sdd_json(k, h_instance)

                # Assign the foreign key on the object
                model["#{meta[:model_name]}_id"] = id
                model.save!
              else
                logger.warn "Class #{klass} does not have instance method 'from_sdd_json'"
              end
            end
          elsif h[k[:xml_name]].is_a? Hash
            logger.debug "#{k[:xml_name]} is a single object, will add only one"
            klass = k[:model_name].camelcase(:upper).constantize
            if klass.respond_to? :from_sdd_json
              model = klass.from_sdd_json(k, h[k[:xml_name]])

              # Assign the foreign key on the object
              model["#{meta[:model_name]}_id"] = id
              model.save!
            else
              logger.warn "Class #{klass} does not have instance method 'from_sdd_json'"
            end
          end
        end
      end
    end
  end

  def fixture_type_enums
    %w(RecessedWithLens RecessedOrDownlight NotInCeiling)
  end

  def lamp_type_enums
    %w(LinearFluorescent CFL Incandescent LED MetalHalide MercuryVapor HighPressureSodium)
  end
end

app/controllers/luminaires_controller.rb
class LuminairesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :project
  before_action :set_luminaire, only: [:show, :edit, :update, :destroy]
  before_action :get_project

  respond_to :json, :html

  def index
    @luminaires = (@project.present?) ? @project.luminaires : []
    respond_with(@luminaires)
  end

  def show
    respond_with(@luminaire)
  end

  def new
    @luminaire = Luminaire.new
    respond_with(@luminaire)
  end

  def edit
  end

  def create
    @luminaire = Luminaire.new(luminaire_params)
    @luminaire.save
    respond_with(@luminaire)
  end

  # receives hash with form {project_id: ..., data: [array of luminaires]}
  def bulk_sync
    luminaires = []

    clean_params = luminaires_params
    logger.info("CLEAN PARAMS: #{clean_params.inspect}")

    # add / update
    if clean_params.key?('data')
      clean_params[:data].each do |rec|
        logger.info("RECORD of type #{rec['type']}:  #{rec.inspect}")
        if rec.key?('id') && !rec['id'].nil?
          @lum = Luminaire.find(rec['id'])
          @lum.update(rec)
        else
          @lum = Luminaire.new(rec)
          @lum.save
        end
        luminaires << @lum
      end

    end

    @project.luminaires = luminaires
    @project.save

    # TODO: add error handling?!
    respond_with luminaires.first || Luminaire.new
  end

  def update
    @luminaire.update(luminaire_params)
    respond_with(@luminaire)
  end

  def destroy
    @luminaire.destroy
    respond_with(@luminaire)
  end

  private

  def set_luminaire
    @luminaire = Luminaire.find(params[:id])
  end

  def get_project
    @project = Project.where(id: params[:project_id]).first
  end

  def luminaires_params
    params.permit(:project_id, :building_id, data: [:id, :name, :fixture_type, :lamp_type, :power, :heat_gain_space_fraction, :heat_gain_radiant_fraction])
  end
end

app/views/luminaires/_form.html.erb
<%= form_for(@luminaire) do |f| %>
  <% if @luminaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@luminaire.errors.count, "error") %> prohibited this luminaire from being saved:</h2>

      <ul>
      <% @luminaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :fixture_type %><br>
    <%= f.text_field :fixture_type %>
  </div>
  <div class="field">
    <%= f.label :lamp_type %><br>
    <%= f.text_field :lamp_type %>
  </div>
  <div class="field">
    <%= f.label :power %><br>
    <%= f.text_field :power %>
  </div>
  <div class="field">
    <%= f.label :heat_gain_space_fraction %><br>
    <%= f.text_field :heat_gain_space_fraction %>
  </div>
  <div class="field">
    <%= f.label :heat_gain_radiant_fraction %><br>
    <%= f.text_field :heat_gain_radiant_fraction %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/luminaires/edit.html.erb
<h1>Editing luminaire</h1>

<%= render 'form' %>

<%= link_to 'Show', @luminaire %> |
<%= link_to 'Back', luminaires_path %>

app/views/luminaires/index.html.erb
<h1>Listing luminaires</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fixture type</th>
      <th>Lamp type</th>
      <th>Power</th>
      <th>Heat gain space fraction</th>
      <th>Heat gain radiant fraction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @luminaires.each do |luminaire| %>
      <tr>
        <td><%= luminaire.name %></td>
        <td><%= luminaire.fixture_type %></td>
        <td><%= luminaire.lamp_type %></td>
        <td><%= luminaire.power %></td>
        <td><%= luminaire.heat_gain_space_fraction %></td>
        <td><%= luminaire.heat_gain_radiant_fraction %></td>
        <td><%= link_to 'Show', luminaire %></td>
        <td><%= link_to 'Edit', edit_luminaire_path(luminaire) %></td>
        <td><%= link_to 'Destroy', luminaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Luminaire', new_luminaire_path %>

app/views/luminaires/new.html.erb
<h1>New luminaire</h1>

<%= render 'form' %>

<%= link_to 'Back', luminaires_path %>

app/views/luminaires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @luminaire.name %>
</p>

<p>
  <strong>Fixture type:</strong>
  <%= @luminaire.fixture_type %>
</p>

<p>
  <strong>Lamp type:</strong>
  <%= @luminaire.lamp_type %>
</p>

<p>
  <strong>Power:</strong>
  <%= @luminaire.power %>
</p>

<p>
  <strong>Heat gain space fraction:</strong>
  <%= @luminaire.heat_gain_space_fraction %>
</p>

<p>
  <strong>Heat gain radiant fraction:</strong>
  <%= @luminaire.heat_gain_radiant_fraction %>
</p>

<%= link_to 'Edit', edit_luminaire_path(@luminaire) %> |
<%= link_to 'Back', luminaires_path %>